# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5

env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=py27
  - TOXENV=py26
  - TOXENV=pypy

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - |
    if [ "$TOXENV" = "pypy" ]; then
      export PYENV_ROOT="$HOME/.pyenv"
      if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
        cd "$PYENV_ROOT" && git pull
      else
        rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
      fi
      export PYPY_VERSION="5.4"
      "$PYENV_ROOT/bin/pyenv" install "pypy-$PYPY_VERSION"
      virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
      source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
    fi
  - pip install -U tox

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}


